# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Generate documentation
      run: |
        cd ${{ github.workspace }}/docs ; \
        find . -name "*.html" -type f -delete ; \
        cd ${{ github.workspace }}/src ; \
        pdoc3 --html . -o ${{ github.workspace }}/docs --force --template-dir ${{ github.workspace }}/docs ; \
        mv ${{ github.workspace }}/docs/src/* ${{ github.workspace }}/docs/
    - name: Commit to repo
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add ./docs/*
        if ! git diff-index --quiet HEAD; then
           git commit -m "Update documentation and coverage badge."
           git fetch origin main
           git push origin HEAD:main
        fi
    - name: Check if gh-pages branch exist
      run: |
        git branch | grep gh-pages || git checkout -b gh-pages
    - name: Copy docs to gh-pages
      run: |
        cp -r ${{ github.workspace }}/docs/* ${{ github.workspace }}
    - name: Pull from remote
      run: |
        git pull --ff-only origin gh-pages
    - name: Commit to gh-pages
      run: |
        git add .
        git commit -m "Update pages documentation"
    - name: Push to gh-pages
      run: |
        git push origin gh-pages
    - name: Set gh-pages as source for GitHub Pages
      run: |
        curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/ConnorS1110/hw2-data -d '{"name":"hw2-data","default_branch":"gh-pages"}'
